[package]
name = "gtk-web"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
curl = "0.4.46"
gtk = "0.18.1"
html5ever = "0.27.0"
url = "2.5.0"
